name: CoolTeleport
version: '1.0'
main: io.github.luka3101.coolTeleport.Main
api-version: '1.21'
authors: [ Luka Antunović ]
commands:
  coolteleport:
    aliases:
      - cooltp
      - ctp
permissions:
  coolteleport.delay.instant:
    description: Allows instant teleport without delay
    default: op
  coolteleport.delay.short:
    description: Allows short teleport delay
    default: false
  coolteleport.delay.long:
    description: Default long teleport delay
    default: true